#!/usr/bin/env bash
set -e

echo "Recommended PTB-XL download location:"
echo "data/raw/ptbxl/"
echo ""
echo "Create directories:"
echo "mkdir -p data/raw/ptbxl data/raw/ptbxl_plus"
echo ""
echo "Install wfdb:"
echo "python -m pip install wfdb"
echo ""
echo "Option A: Download manually from PhysioNet PTB-XL and extract into data/raw/ptbxl/"
echo "Required files:"
echo "  ptbxl_database.csv"
echo "  scp_statements.csv"
echo "  records100/"
echo "  records500/ optional"
echo ""
echo "Optional PTB-XL+ location:"
echo "  data/raw/ptbxl_plus/"
echo ""
echo "Option B: Use wget if available and permitted by your PhysioNet access:"
echo "wget -r -N -c -np https://physionet.org/files/ptb-xl/1.0.3/ -P data/raw/physionet_download/"
echo ""
echo "PTB-XL+ may need to be downloaded separately from its PhysioNet page if required for multimodal modeling."
echo ""
echo "After download, move or symlink files so that:"
echo "data/raw/ptbxl/ptbxl_database.csv"
echo "data/raw/ptbxl/scp_statements.csv"
echo "data/raw/ptbxl/records100/"
echo "data/raw/ptbxl/records500/"
echo ""
echo "Then run:"
echo "bash scripts/00b_validate_local_data_layout.sh"
echo "bash scripts/00a_discover_data_paths.sh"
echo "bash scripts/00_check_data_feasibility.sh"
echo "bash scripts/01_prepare_ptbxl.sh"
echo ""
echo "If download fails because of network, login, or license restrictions, download manually from PhysioNet and place the files in the same layout."
